version: 2
models:
  - name: emp_actif_fact_base
    config:
      tags: 
        - emp_actif
    description: >
      Active table.
      Map all employes which are active
    columns:
      - name: matr
        description: The unique identifier of an employee.     