version: 2

models:
  - name: stg_activity_history
    description: >
      This table is a re-implementation of pai_dos_empl with all historical data.
      The table list all `experiences` of a given employee.
      An experience is defined as a period of time during which an employee has an unchanged job category, workplace, employment status, and engagement status.

    columns:
      - name: matr
        description: The unique identifier of an employee.
      - name: school_year
        description: The school year (from september the first to august the 31 of the following year) for which the status mapping is valid.
      - name: ref_empl
        description: The unique identifier of an employment.
      - name: corp_empl
        description: The job category of the employment.
      - name: etat_empl
        description: The employment status of the employment.
      - name: stat_eng
        description: The engagement status of the employment.
      - name: lieu_trav
        description: The workplace of the employment.
      - name: date_eff
        description: The date at which the employment started.
      - name: date_fin
        description: The date at which the employment ended.
    tests:
      - accepted_values_from_ref:
          target_column: etat_empl
          ref_table: ref('dim_employment_status_yearly')
          ref_column: etat_empl
          target_join_fields:
            - school_year
          ref_join_fields:
            - school_year

  - name: stg_main_job_history
    description: >
      Provide the history of main jobs for each employee.
      The table is represented as a from -> to table, meaning that each row represent a period of time during which the employee had the same main job.

    columns:
      - name: school_year
        description: The school year (from september the first to august the 31 of the following year) for which the status mapping is valid.
      - name: matr
        description: The unique identifier of an employee.
      - name: main_job
        description: The main job of the employee for the given school year. Can be joined on a ref_empl
      - name: valid_from
        description: The date at which the main job started.
      - name: valid_until
        description: The date at which the main job ended (excluded).
